### ISSUE TITLE
Meteor does not currently support objects other than ObjectID as ids

### ISSUE THREAD

**Issue by nirarazi** [JcBernack/meteor-reactive-aggregate#22]
Hi,

Trying to use this plugin for the first time.

Upon publishing I get the following error:

> Error: Meteor does not currently support objects other than ObjectID as ids

This happens when `sub.added` and `sub.changed` are called.
Executing the aggregate and then manually running the same functions on the subscription object, it seems to accept strings but not `ObjectID` objects.

So, to me, the issue seems to be the fact that `obj._id` is being passed as the second parameter, rather than `obj._id.toHexString()`.

Has anyone run into this situation?
Am I missing something?

I am running Meteor 1.4.2 and v0.7.0 of the package.

THANKS!

**Comment by JcBernack** [comment]
Please make sure all the IDs in your collection are strings and not ObjectIDs. Awkward things happen if both are mixed.

**Comment by msolters** [comment]
I have this problem as well.  I don't think this is a mixing of string and ObjectIDs.  I think this is a byproduct of using the `$group` action in your pipeline, such that the resulting `_id` of the post-pipeline docs is a data object (NOT an ObjectID).

Then, later, in https://github.com/JcBernack/meteor-reactive-aggregate/blob/master/aggregate.js#L18 and https://github.com/JcBernack/meteor-reactive-aggregate/blob/master/aggregate.js#L20, when this object is passed as `doc._id`, we get the error because the object is not an ObjectID.

**Comment by msolters** [comment]
My fix is usually to do something like this:

```js
function update() {
    if (initializing) return;
    // add and update documents on the client
    collection.aggregate(pipeline).forEach(function (doc) {
      doc.group_id = doc._id; // move the common properties in ._id from the $group step into a new property
      doc._id = Random.id(); // give the document a new Mongo ID (string)
      if (!sub._ids[doc._id]) {
        sub.added(options.clientCollection, doc._id, doc);
      } else {
        sub.changed(options.clientCollection, doc._id, doc);
      }
      sub._ids[doc._id] = sub._iteration;
    });
    ...
```

Note that you can also accomplish the `doc.group_id = doc._id` replacement step in thepipeline itself, using projections.

This does solve the error stated in this issue.  It could be PR'd: the problem here is that some assumption must be made about what to name the variable that stores the `$group` dimensions.  I throw what used to be my `._id` into `.group_id` but there are better ways to name that, and any choice we make could collide with real properties some user out there might have.

**Comment by JcBernack** [comment]
Ok, I see the problem now, but your fix has a problematic flaw: You assign new random ids to all documents in the aggregated result, which means that every time the client collection should be updated you remove and re-add every single document.

**Comment by msolters** [comment]
Good point.  If we can deterministically hash the original `._id` objects into unique strings, though, those can be the keys in our new dictionary.

**Comment by msolters** [comment]
Surely the simplest keys would be `let doc_id = JSON.stringify( doc._id )`

**Comment by Infinitism** [comment]
The way I went about solving this by creating an "_id" in the $project that $concat-ed 3 different fields that I knew would be unique for each result returned but doesn't create a new "_id" if that document changes. 

`$project: {
_id: {$concat: ["$itemID", "$count", "$itemName"]
}`

This way the "_id" is unique for each grouping which is counting the number of items in each category. Eg: 5 shampoos in Dog care. 

When the count changes, it only removes the old object and inserts the new one. Also when the $match in your pipeline makes the document obselete (because you only want to return product purchased in the last 5mins) the client removes this old shampoo query because it has the unique "_id" we created. 

I had the issue with "Removed nonexistent document jahfsd345345" and that's how I resolved it which should also resolve the ObjectID issue you are facing. 

Also, thanks for the great package @JcBernack . I was able to figure this out with your input as well @msolters .

**Comment by themao** [comment]
Great solution @Infinitism, thanks a lot! I'm not too advanced in MongoDB so didn't know about the $concat operator.

@JcBernack at first I followed @msolters way - copied your library code and changed the ID generation. Now, since I know 2 solutions already, how do you think, would it be better to extend the library with stringified ID generation or something like this, or maybe just to extend the documentation with the $concat example?

UPD: I'd vote for automated transformation on stringifying, because in my case there's a problem with timestamp, so id generation becomes like this:

`_id: {
                    $concat: [
                        '$_id.userId',
                        '$_id.projectId',
                        { $substr: ['$_id.timestamp', 0, -1] }
                    ]
                }`

And if there's a Date object, it will become even more complicated, because each day, month and year would need to be substr'd separately.

**Comment by wcrisman** [comment]
Creating an id from $concat is fine if all your key fields are strings, but does not appear to work if any field is of a different type.  

In my particular case, I am using $year: '$date' and $week: '$date' to group my results by year and week.  Unfortunately it appears that mongo outputs numbers and not strings for these values.  Concat complains about not being able to put two integers together in a string, and there appears to be no good way to convert them to strings in the query.  Of course I have only been using mongo for two weeks now, so perhaps I missed that bit of documentation.  

It would be nice to be able to create a formatted string in mongo similar to `_id: {$format: ['$year', ' - ', '$week']}`, or `_id: {$format: ['%d - %d, '$year', '$week']}`

**Comment by wcrisman** [comment]
I should note that using `$dateToString: {format: '%V', date: '$date'}` will convert the number into a string, and for the specific example I mentioned above it will fix the problem of $concat not accepting non-string values.

That doesn't change the overall problem however since it is quite likely someone would wish to group by a numeric field.

**Comment by themao** [comment]
@wcrisman there's a way to bypass that limitation by using $substr function like I did. Here's something similar to your case http://stackoverflow.com/questions/14989058/mongo-new-date-in-aggregate-project

**Comment by AthmaneKhl** [comment]
Hi, I know this is an old issue,
Creating an _id from $concat or $dateToString doesn't suit my need.

In my case I want to get the _id ( which is a meteor ObjectID ) as _id._str is there a way to do this ?

**Comment by terzo-genito** [comment]
I have verified that in the Mongo Shell that my ids are ObjectIDs (all and no strings), yet I still get this error. Any thoughts on how to circumvent?

**Comment by rkstar** [comment]
@DrokTor i don't know if this will work inside an aggregation, but you can try it:
`stringId: '$_id.str` or `stringId: _id.toString()` assuming `_id` is actually a mongo `ObjectId`

https://docs.mongodb.com/manual/reference/method/ObjectId/#ObjectId

**Comment by AthmaneKhl** [comment]
@rkstar 

I chose another path to do what I was looking for and went without this package.

Thank you for your concern .

**Comment by cormip** [comment]
What's easily overlooked is that this will NOT work:

```javascript
ReactiveAggregate(this, ApartmentResidents, [
        {$match: qry},
        {$group: {_id : {month : {$month: "$moveInDate"}, year : {$year: "$moveInDate"}, property_id: "$property_id" }, total : {$sum : 1}}},
        {$project: {_id: "$_id.property_id", month : "$_id.month", year : "$_id.year", total : "$total"}}
    ], { clientCollection: "MonthlyMoveIns" })
```
**It does not return all the records apparently because the _id returned is not unique.** You need to instead do something like this to create unique _id's for each returned record.
```javascript
ReactiveAggregate(this, ApartmentResidents, [
        {$match: qry},
        {$group: {_id : {month : {$month: "$moveInDate"}, year : {$year: "$moveInDate"}, property_id: "$property_id" }, total : {$sum : 1}}},
        {$project: {_id: {$concat: ["$_id.property_id", {$substr:["$_id.month",0,-1]}, {$substr:["$_id.year",0,-1]}]}, property_id: "$_id.property_id", month : "$_id.month", year : "$_id.year", total : "$total"}}
    ], { clientCollection: "MonthlyMoveIns" })
```
What threw me for a loop was that Studio 3T for MongoDB had no problem at all returning all records correctly for the first aggregation pipeline above.

**Comment by radovansurlak** [comment]
In my case, I've found a solution in here https://stackoverflow.com/a/46021553/6568507.
Using `$project` part in the pipeline and adding an `_id` there manually as such:

```[
    {
        "$match": {
            "time": {$gte: fromDate, $lte: toDate},
            "userId": {'$regex' : regex}
        }
    },
    {
        $group : {
            "_id": {
                "userId": "$userId",
                "date": { $dateToString: { format: "%Y-%m-%d", date: "$time" } }
            },
            "maxId": { "$max": "$_id" },
            "total": { "$sum": 1 }
           }
    },
    // Add the reshaping to the end of the pipeline
    {
        "$project": {
            "_id": "$maxId",           // replaced _id
            "userDate": "$_id",       // the renamed compound key
            "total": 1
        }
    }
]```

**Comment by JcBernack** [comment]
Closing old issues.
