### ISSUE TITLE
Delay between subscription.ready() and data availability

### ISSUE THREAD

**Issue by qualitymanifest** [JcBernack/meteor-reactive-aggregate#48]
First, I'd just like to say thank you for creating this package! This is really cool. Now, for the problem I'm encountering:

For trying out this package, I have two identical versions of my app running - The only difference being that one subscribes to an aggregate collection that I create outside of meteor and update via a cronjob, and one uses meteor-reactive-aggregate to aggregate the data in real time. Either way, the aggregated data is the exact same size, format, everything.

- With the app version that aggregates outside of meteor, when `subscription.ready()` is true, the data is always instantly available on the client, even on slow client connections.

- With the app version that uses meteor-reactive-aggregate, when `subscription.ready()` is true, I have an empty array where the data should be. It is easy to check if the array is empty (and if so, continue displaying a loading spinner). The problem is that on slow client connections, **after** the array is empty but **before** the array is completely filled, the array will often be partially filled which causes my component to render the partial data before the array is completely filled and the final render happens.

Any idea as to what may be causing this, and if there is anything I can do about it? Is `ready()` being called early, or is the server just kind of bogged down from performing the aggregation, so it takes longer to publish the data?

**Comment by JcBernack** [comment]
I'm pretty sure this is a bug.

Have a look here:
https://github.com/JcBernack/meteor-reactive-aggregate/blob/master/aggregate.js#L81
The call to `subscription.ready()` clearly comes after the first full update.

I think this is caused by the way the update-throttling was implemented. It causes the `update` function to be asynchronous and therefore the subscription is immediatly set to ready. There is an obvious fix for that: The first update has to be synchronous, without throttle. Can you submit a PR with a fix? I can't say if or when I have the time to do it myself.

**Comment by qualitymanifest** [comment]
Took me a while to figure it out but I think I've got it. The problem is that the `.forEach` running on the aggregation cursor has an asynchronous callback, so you need to wait until there are no more documents remaining in the cursor before marking the subscription ready. I removed the original `subscription.ready()` and changed the cursor `.forEach` to an `.each` since that gives you a `null` in place of a document when there are none left. Then when you get `null`, remove errant documents and mark the subscription ready.

I'll submit a PR in a bit
