### ISSUE TITLE
observeOptions does nothing / can't use limit and skip

### ISSUE THREAD

**Issue by onlysli** [JcBernack/meteor-reactive-aggregate#51]
Hello,
The documentation says that I can use 'limit' like this:
```
observeOptions: {
        limit: 10,
        skip: 0,
        sort: { createdAt: -1 },
}
```
It does not work, i always get all the documents that corresponds to the query.

Also, i tried adding limit directly in the pipeline:
```
{
      $lookup: {
        from: 'users',
        localField: 'userId',
        foreignField: '_id',
        as: 'user'
     }
}, 
{
      $project: _adsPublicFields
}, 
{
      $limit: 10
},
{
      $skip: 0
}, 
{
      $sort:  { createdAt: -1 },
}
```
This works only if skip is 0, if skip is 10, it will retun empty, if skip is 6, it will return 4 results (the limit 10 - skip 6).

What can i do to make it work?

**Comment by jbx-alex** [comment]
Hello @onlysli,

I have had the same problem, I am using this library https://github.com/robfallows/tunguska-reactive-aggregate (it's a reworks of jcbernack:reactive-aggregate for ES6/ES7 and Promises) and it seems that this is because of the order of the parameters, try to put it like this:

```
{
    $sort:  { createdAt: -1 }
},
{
    $limit: 10  
}, 
{
    $skip: 0
}
```
I add the link of my example https://github.com/robfallows/tunguska-reactive-aggregate/issues/12

Regards.

**Comment by JcBernack** [comment]
Closing old issues.
